### ISSUE TITLE
Improvements to the binary tarball

### ISSUE THREAD

**Issue by Thirumalai-Shaktivel** [Thirumalai-Shaktivel/lfortran#101]
* [ ] Get the default dynamic linking working (#178)
* [ ] Make it work without specifying `LFORTRAN_RUNTIME_LIBRARY_DIR` (#180)
* [ ] Add a few examples that work with the compiler already (#181)
* [ ] Add a README
